package com.demo.adventure.engine.command;

public enum TokenType {
    // Actions
    EAT, DROP, MOVE, GO, INSPECT, INVENTORY, JUMP, LOOK, LISTEN, MAKE, OPEN, PLACE, PUT, SEARCH, SOAK, STASH, STRIKE, SWIM, TAKE,
    USE, HOW, QUIT, FLEE,

    // Directions
    NORTH, NORTH_EAST, EAST, SOUTH_EAST, SOUTH, SOUTH_WEST, WEST, NORTH_WEST, UP, DOWN,

    // Keywords
    FROM, IN, INTO, ON, TO, USING, WITH, HELP, AWAY,

    // Types
    IDENTIFIER, NUMBER, STRING, THING, FUNCTION,

    // Key Expression
    LEFT_PAREN, RIGHT_PAREN, COMMA, DOT, POINTER, MINUS, PLUS, STAR, SLASH, NEGATE,
    LESS_THAN, LESS_THAN_OR_EQUAL, GREATER_THAN, GREATER_THAN_OR_EQUAL,
    LEFT_ANGLE_BRACKET, RIGHT_ANGLE_BRACKET, LEFT_BRACKET, RIGHT_BRACKET, COLON, SEMICOLON,
    TRUE, FALSE, AND, OR, NOT, EQUAL, NOT_EQUAL,
    LITERAL_STRING, INTERPOLATED_STRING_START, INTERPOLATED_STRING_END,

    UNSPECIFIED,

    EOL
}
