package com.demo.adventure.authoring.gardener;

import java.util.UUID;

/**
 * Patch generated by the Gardener when updating a fixture description.
 *
 * @param thingId             fixture id
 * @param previousDescription original description text
 * @param newDescription      updated description text
 * @param author              source marker, defaults to "gardener" when blank
 */
public record GardenerDescriptionPatch(
        UUID thingId,
        String previousDescription,
        String newDescription,
        String author
) {
    public GardenerDescriptionPatch {
        if (thingId == null) {
            throw new IllegalArgumentException("thingId is required");
        }
        author = (author == null || author.isBlank()) ? "gardener" : author;
    }
}
